name: custom test workflow
on: push

jobs:
  checkout:
    name: custom checkout action exercise
    runs-on: ubuntu-latest
    steps:
      - run: ls -al
        name: custom run ls -al
      - uses: actions/checkout@v4
      - run: ls -al
        name: 2nd ls -al
      - run: cat .github/workflows/checkout.yaml
        name: cat