name: main workflow
on: push

jobs:
  checkout:
    name: custom checkout action exercise
    runs-on: ubuntu-latest
    steps:
      - run: ls -al
        name: custom run ls -al
      - uses: actions/checkout@v4
        with:
          path: our-source
      - run: ls -al our-source
        name: 2nd ls -al
      - run: cat our-source/.github/workflows/main.yaml
        name: cat